// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/FelixAnna/web-service-dlw/memo-api/memo"
	"github.com/FelixAnna/web-service-dlw/memo-api/memo/repository"
	"github.com/FelixAnna/web-service-dlw/memo-api/memo/services"
)

// Injectors from wire.go:

func InitialMemoApi() memo.MemoApi {
	memoRepoDynamoDB := repository.ProvideMemoRepoDynamoDB()
	dateService := services.ProvideDateService()
	memoApi := memo.MemoApi{
		Repo:        memoRepoDynamoDB,
		DateService: dateService,
	}
	return memoApi
}
