// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/FelixAnna/web-service-dlw/date-api/date"
	"github.com/FelixAnna/web-service-dlw/date-api/date/services"
)

// Injectors from wire.go:

func InitialDateApi() date.DateApi {
	carbonService := services.ProvideCarbonService()
	dateApi := date.ProvideDateApi(carbonService)
	return dateApi
}
