trigger:
  branches:
    include:
    - develop
  paths:
    include:
      - src/
      - azure-pipelines.yml
parameters:
  - name: environment
    displayName: Where to deploy?
    type: string
    default: dev
    values:
    - prod
    - dev
  - name: imageTag
    displayName: Docker image tag
    type: string
    default: latest
    
variables:
- group: ${{parameters.environment}}-variable-group
- name: env
  value: ${{parameters.environment}}
- name: imageTag
  value: ${{parameters.imageTag}}

pool:
  name: Azure Pipelines
  vmImage: 'ubuntu-latest'
  
jobs:
- job: provisioningInfrastructure
  displayName: Apply infrastructure # Human-readable name for the job. 
  timeoutInMinutes: 10

  steps:
  - task: TerraformInstaller@1    
    displayName: install terraform

  - task: TerraformCLI@1
    displayName: 'terraform initial'
    inputs:
      command: init
      workingDirectory: 'devops/aks_nginx/terraform/profiles/$(env)'
      backendType: azurerm
      backendServiceArm: 'dlw-azure-service-principal'
      backendAzureRmSubscriptionId: '$(ARM_SUBSCRIPTION_ID)'
      backendAzureRmResourceGroupName: 'felix-configuration-rg'
      backendAzureRmStorageAccountName: configstoragefelix
      backendAzureRmContainerName: tfstate
      backendAzureRmKey: 'dlw-$(env).nginx.tfstate'

  - task: TerraformCLI@1
    displayName: 'terraform plan'
    inputs:
      command: plan
      workingDirectory: 'devops/aks_nginx/terraform/profiles/$(env)'
      environmentServiceName: 'dlw-azure-service-principal'
      providerAzureRmSubscriptionId: '$(ARM_SUBSCRIPTION_ID)'
      runAzLogin: true
      backendServiceArm: 'dlw-azure-service-principal'
      backendAzureRmSubscriptionId: '$(ARM_SUBSCRIPTION_ID)'
      backendAzureRmResourceGroupName: 'felix-configuration-rg'
      backendAzureRmStorageAccountName: configstoragefelix
      backendAzureRmContainerName: tfstate
      backendAzureRmKey: 'dlw-$(env).nginx.tfstate'
      publishPlanResults: 'dlw-$(env)-plan'
      providerServiceAws: 'aws connection'
      providerAwsRegion: '$(AWS_DEFAULT_REGION)'

  - task: TerraformCLI@1
    displayName: 'terraform apply'
    inputs:
      command: apply
      workingDirectory: 'devops/aks_nginx/terraform/profiles/$(env)'
      environmentServiceName: 'dlw-azure-service-principal'
      providerAzureRmSubscriptionId: '$(ARM_SUBSCRIPTION_ID)'
      runAzLogin: true
      commandOptions: '-auto-approve'
      providerServiceAws: 'aws connection'
      providerAwsRegion: '$(AWS_DEFAULT_REGION)'

- job: deployServices
  displayName: Deploy All Services # Human-readable name for the job. 
  dependsOn: provisioningInfrastructure
  timeoutInMinutes: 10

  steps:
  - task: AzureCLI@2
    displayName: 'Replace Keys & Tags'
    inputs:
      azureSubscription: 'dlw-azure-service-principal'
      scriptType: bash
      scriptLocation: inlineScript
      inlineScript: |
        az login --service-principal --username="${ARM_CLIENT_ID}" --password="${ARM_CLIENT_SECRET}" --tenant=${ARM_TENANT_ID}
        sed -i "s/awsKeyIdPlaceHolder/$(echo -n $(AWS_ACCESS_KEY_ID) | base64)/" ./$(app)-chart/values_aks_$(env).yaml
        sed -i "s/awsSecretKeyPlaceHolder/$(echo -n $(AWS_SECRET_ACCESS_KEY) | base64)/" ./$(app)-chart/values_aks_$(env).yaml
        sed -i "s/imageVersion/$(imageTag)/" ./$(app)-chart/values_aks_$(env).yaml
      workingDirectory: 'devops'

  - task: AzureCLI@2
    displayName: 'Deploy Basic Charts'
    inputs:
      azureSubscription: 'dlw-azure-service-principal'
      scriptType: bash
      scriptLocation: inlineScript
      inlineScript: |
        sh basic_services.sh $(env) $(app)
      useGlobalConfig: true
      workingDirectory: 'devops/aks_nginx/services'

  - task: AzureCLI@2
    displayName: 'Deploy Main Charts'
    inputs:
      azureSubscription: 'dlw-azure-service-principal'
      scriptType: bash
      scriptLocation: inlineScript
      inlineScript: |
        sh main_services.sh $(env) $(app)
      useGlobalConfig: true
      workingDirectory: 'devops/aks_nginx/services'

