// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package dependencyInjection

import (
	"github.com/FelixAnna/web-service-dlw/finance-api/zdj"
	"github.com/FelixAnna/web-service-dlw/finance-api/zdj/repository"
)

// Injectors from wire.go:

func InitializeApi() (zdj.ZdjApi, error) {
	zdjSqlServerRepo, err := repository.ProvideZdjSqlServerRepo()
	if err != nil {
		return zdj.ZdjApi{}, err
	}
	zdjApi := zdj.ProvideZdjApi(zdjSqlServerRepo)
	return zdjApi, nil
}
