// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/FelixAnna/web-service-dlw/user-api/auth"
	"github.com/FelixAnna/web-service-dlw/user-api/users"
	"github.com/FelixAnna/web-service-dlw/user-api/users/repository"
)

// Injectors from wire.go:

func InitialUserApi() users.UserApi {
	userRepoDynamoDB := repository.ProvideUserRepoDynamoDB()
	userApi := users.UserApi{
		Repo: userRepoDynamoDB,
	}
	return userApi
}

func InitialGithubAuthApi() auth.GithubAuthApi {
	userRepoDynamoDB := repository.ProvideUserRepoDynamoDB()
	githubAuthApi := auth.ProvideGithubAuth(userRepoDynamoDB)
	return githubAuthApi
}
