name: ci

on:
  push:
    branches:
      - 'master'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout 
        uses: actions/checkout@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build and push date-api
        uses: docker/build-push-action@v2
        with:
          context: ./date-api
          file: ./date-api/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/dlw-date-api:latest
      -
        name: Build and push memo-api
        uses: docker/build-push-action@v2
        with:
          context: ./memo-api
          file: ./memo-api/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/dlw-memo-api:latest
      -
        name: Build and push finance-api
        uses: docker/build-push-action@v2
        with:
          context: ./finance-api
          file: ./finance-api/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/dlw-finance-api:latest
      -
        name: Build and push user-api
        uses: docker/build-push-action@v2
        with:
          context: ./user-api
          file: ./user-api/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/dlw-user-api:latest
